# DROP TABLE CUST_ORDERS;
# DROP TABLE SPECIAL_ORDERS;
# DROP TABLE TEMP;
# DROP TABLE ACCOUNTS;
# DROP TABLE ACTION;

CREATE TABLE CUST_ORDERS
( ORDER_NO      INT(12),
  PRODUCT_ID    INT(6),
  ARRIVAL_DATE  DATE,
  CONSTRAINT CUST_ORDERS_ORDER_NO_PK PRIMARY KEY(ORDER_NO));

INSERT INTO CUST_ORDERS VALUES(1,1,NULL);
INSERT INTO CUST_ORDERS VALUES(2,1,NULL);
INSERT INTO CUST_ORDERS VALUES(3,2,NULL);
INSERT INTO CUST_ORDERS VALUES(4,1,NULL);
INSERT INTO CUST_ORDERS VALUES(5,2,NULL);
INSERT INTO CUST_ORDERS VALUES(6,3,NULL);

CREATE TABLE SPECIAL_ORDERS
( ORDER_ID      INT(6),
  PRODUCT_ID    INT(6),
  ORDER_QTY     INT(3),
  CONSTRAINT SPECIAL_ORDERS_ORDER_ID_PK PRIMARY KEY(ORDER_ID));

CREATE TABLE TEMP
( COL1      DEC(9,4),
  COL2      DEC(9,4),
  MESSAGE   VARCHAR(55),
  CONSTRAINT TEMP_COL1_PK PRIMARY KEY(COL1));

CREATE TABLE ACCOUNTS
( ACCOUNT_ID      INT(4),
  BAL             DEC(11,2),
  CONSTRAINT ACCOUNTS_ACCOUNT_ID_PK PRIMARY KEY(ACCOUNT_ID));

INSERT INTO ACCOUNTS VALUES(1,1000);
INSERT INTO ACCOUNTS VALUES(2,2000);
INSERT INTO ACCOUNTS VALUES(3,1500);
INSERT INTO ACCOUNTS VALUES(4,6500);
INSERT INTO ACCOUNTS VALUES(5,500);


CREATE TABLE ACTION
( ACCOUNT_ID      INT(4),
  OPER_TYPE       VARCHAR(1),
  NEW_VALUE       DEC(11,2),
  CONSTRAINT ACTION_ACCOUNT_ID_PK PRIMARY KEY(ACCOUNT_ID));

INSERT INTO ACTION VALUES(3,'U',599);
INSERT INTO ACTION VALUES(6,'I',2099);
INSERT INTO ACTION VALUES(7,'U',1599);
INSERT INTO ACTION VALUES(1,'I',399);
